# Today we will learn to Jupyter Lab

### TWe are discussing about jupyter shortcuts

In [11]:
print("Helloooo")

Helloooo


In [1]:
import numpy as np

# Create a 5x5 "image" of random integers from 0 to 255
image = np.random.randint(0, 256, size=(5, 5))
print("Original Image (pixel values):")
print(image)

# Create a boolean mask for all pixels with brightness > 150
bright_pixels_mask = image > 150
print("\nMask (True where pixels are bright):")
print(bright_pixels_mask)

# Use the mask to add 50 brightness points to only the bright pixels
# This is a powerful one-liner!
image[bright_pixels_mask] += 50

print("\nBrightened Image (values > 150 increased by 50):")
print(image)

Original Image (pixel values):
[[152 145  31  72 124]
 [ 63  82 212  34  40]
 [ 81  91  98 213  78]
 [ 39 109   4 158  15]
 [ 27 243 159  11 248]]

Mask (True where pixels are bright):
[[ True False False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False  True False]
 [False  True  True False  True]]

Brightened Image (values > 150 increased by 50):
[[202 145  31  72 124]
 [ 63  82 262  34  40]
 [ 81  91  98 263  78]
 [ 39 109   4 208  15]
 [ 27 293 209  11 298]]


In [2]:
np.save('test1.npy', image)

In [4]:
import numpy as np

# Create a 5x5 "image" of random integers from 0 to 255
image = np.random.randint(0, 256, size=(5, 5))
print("Original Image (pixel values):")
print(image)

# Create a boolean mask for all pixels with brightness > 150
bright_pixels_mask = image > 150
print("\nMask (True where pixels are bright):")
print(bright_pixels_mask)

# Use the mask to add 50 brightness points to only the bright pixels
image[bright_pixels_mask] += 50

# Create masks for values outside the valid range
over_mask = image > 255  # Values that exceed 255
under_mask = image < 0   # Values that go below 0

print(f"Over mask matrix: {over_mask}")
# Use masks to set values to the valid range
image[over_mask] = 255
image[under_mask] = 0

print("\nBrightened Image (values > 150 increased by 50, constrained to 0-255 with masks):")
print(image)

Original Image (pixel values):
[[ 79  86  22 201 127]
 [195  19 129 233 168]
 [ 61  38  46 106  86]
 [ 84 218 240  10 201]
 [196 127  39 103 181]]

Mask (True where pixels are bright):
[[False False False  True False]
 [ True False False  True  True]
 [False False False False False]
 [False  True  True False  True]
 [ True False False False  True]]
Over mask matrix: [[False False False False False]
 [False False False  True False]
 [False False False False False]
 [False  True  True False False]
 [False False False False False]]

Brightened Image (values > 150 increased by 50, constrained to 0-255 with masks):
[[ 79  86  22 251 127]
 [245  19 129 255 218]
 [ 61  38  46 106  86]
 [ 84 255 255  10 251]
 [246 127  39 103 231]]
