In [1]:
print("Hello world")

Hello world


In [4]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com


In [5]:
# importing numpy library as np
import numpy as np

In [16]:
# Creating 1D Array from a list
list_1 = [1, 2, 3, 4, 5, 6]
array_1d = np.array(list_1)
print(array_1d)
print(array_1d.shape)

[1 2 3 4 5 6]
(6,)


In [17]:
# Creating 2d array from two lists
list_2 = [8, 9, 10, 11, 12, 13]
array_2d = np.array([list_1, list_2])
print(array_2d)
print(array_2d.shape)  # (rows, columns)

[[ 1  2  3  4  5  6]
 [ 8  9 10 11 12 13]]
(2, 6)


In [20]:
# Reshape the array_2d from (2,6) to (4,3)
array_4d = array_2d.reshape(4,3)
print(array_4d)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]
 [11 12 13]]


In [21]:
array_6 = np.arange(11, 33, 2)
print(array_6)
print(array_6.shape)

[11 13 15 17 19 21 23 25 27 29 31]
(11,)


In [25]:
array_7 = np.zeros((4,3))
print(array_7)
print(array_7.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(4, 3)
